import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Button, Container, Heading, List, ListIcon, ListItem, Text } from '@chakra-ui/react'
import { PreviousClients, ServicesWeOffer } from '@/components/Layout'
import {MdCheckCircle} from 'react-icons/md'
import { ContactForm } from '@/components/ContactForm'

  const firstList = ['Kansas Local, with projects across the states.', 'Over 20 years of experience', 'Great Turn around Time', 'Free Quotes.', 'Licensed and Insured'];

  export function ListCreator({sectionName}:any){

    const ListCreator = firstList.map((listItem:string, index:any)=>{
      return(
        <ListItem key={`${index}-${sectionName}`}>
          <ListIcon as={MdCheckCircle} color={'green.500'}/>
          {listItem} 
        </ListItem>
    )})
    return ListCreator

  }


export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={styles.heroSection}>
          <div className={styles.heroCard}>
            <Container>
              <Heading fontFamily={'adamina'} textAlign={'center'}>Welcome to Capital Stone</Heading>
              <Text py={4} px={4}>Kansas leading export in Stucco, Stone,
                and foundation repair on commercial and residential
                projects. Guaranteed!!
              </Text>
              <Container display={'flex'}  flexDirection={{base: 'column', sm: 'row'}} alignItems={'center'} justifyContent={{base: 'center', sm: 'space-evenly'}} >
                <Button as='a' bg={'var(--primary-blue)'} mb={{base: '20px', sm: '0'}} w={'175px'}>Get a Free Estimate</Button>
                <Button as='a' bg={'var(--primary-blue)'} w={'175px'}>View Projects</Button>
              </Container>
            </Container>
          </div>
        </div>
        <PreviousClients/>
        <Section3/>
        <Section4/>
        <Section5/>
        <ServicesWeOffer/>
        <ContactForm/>
      </main>
    </>
  )
}

export function Section3(){
  return(<>
    <div className={styles.section3}>
          <Image src='/curves/curve-1.png'
            width={1440}
            height={170}
            alt="background curve"
            quality={'100'}
            className={styles.curveOne}
          />
            <Image src='/image.JPG'
              width={600}
              height={600}
              alt="image one"
              className={styles.section3Image}
            />
          <Image src='/bg/index-bg-1.png'
              width={500}
              height={500}
              alt="image one"
              className={styles.section3bg}
            />
          <div className={styles.section3TextContainer}>
            <Container>
              <Heading fontFamily={'adamina'} fontSize={'3xl'} textAlign={'center'} py={5}>Stone Projects</Heading>
              <List>
                <ListCreator sectionName="hello"/>
              </List>
            </Container>
          </div>
        </div>
  </>)
}

export function Section4(){
  return(<>
      
    <div className={styles.section4}>
      <div className={styles.section4TextContainer}>
        <Container color={'white'}>
          <Heading fontFamily={'adamina'} fontSize={'3xl'} textAlign={'center'} py={5}>Stucco For All</Heading>
          <List>
            <ListCreator sectionName="newSection"/>
          </List>
        </Container>
      </div>
      <Image src='/bg/index-bg-2.png'
              width={500}
              height={500}
              alt="image one"
              className={styles.section4bg}
      />
      <Image src='/image.JPG'
              width={600}
              height={600}
              alt="image one"
              className={styles.section4Image}
            />
    </div>
  </>)
}

export function Section5(){
  return(<>
    <div className={styles.section5}>
      <Image src='/image.JPG'
        width={600}
        height={600}
        alt="image one"
        className={styles.section5Image}
      />
      <Image src='/bg/index-bg-3.png'
          width={500}
          height={500}
          alt="image one"
          className={styles.section5bg}
      />
      <div className={styles.section5TextContainer}>
        <Container>
          <Heading fontFamily={'adamina'} fontSize={'3xl'} textAlign={'center'} py={5}>Stone Projects</Heading>
          <List>
          <ListCreator sectionName="lastSection"/>
          </List>
        </Container>
      </div>
    </div>
  </>)
}